# Global configuration for phasing project

# location of project on your computer/server
base_dir: "/net/snowwhite/home/beckandy/research/phasing_clean"
chrom: "1"
trio_result_dir: "output/trio_phase_1/no_th"
